### ISSUE TITLE
games-emulation/retroarch-1.7.2.ebuild version bump.

### ISSUE THREAD

**Issue by jason-oliveira** [stefan-gr/abendbrot#112]
I did have to comment-out retroarch-{PV}-disable_wifi_menu.patch because it doesn't seem to work with either 9999 or 1.7.2. Otherwise, symlinking -9999 with the new version number (and all the patches) was sufficient to get it to build.

**Comment by jason-oliveira** [comment]
RA updated to 1.7.3 today. built fine with above caveats.

**Comment by stefan-gr** [comment]
I updated all depending libretro builds to this too. I hope i didn't break anything while at it. Still no gentoo at home.

**Comment by jason-oliveira** [comment]
nope. nothing is broken.
