### ISSUE TITLE
games-emulation/retroarch: "python" USE Flag Broken

### ISSUE THREAD

**Issue by leycec** [stefan-gr/abendbrot#26]
Emerging `retroarch` with the `python` USE flag enabled currently fails with the following fatal error:

    >>> Emerging (12 of 12) games-emulation/retroarch-9999::abendbrot
     * No Python implementation selected for the build. Please set
     * the PYTHON_SINGLE_TARGET variable in your make.conf to one
     * of the following values:
     * 
     * python3_3 python3_4
    
     * ERROR: games-emulation/retroarch-9999::abendbrot failed (setup phase):
     *   No supported Python implementation in PYTHON_SINGLE_TARGET/PYTHON_TARGETS.
     * 
     * Call stack:
     *                 ebuild.sh, line  93:  Called pkg_setup
     *     retroarch-9999.ebuild, line  69:  Called python-single-r1_pkg_setup
     *   python-single-r1.eclass, line 446:  Called python_setup
     *   python-single-r1.eclass, line 436:  Called die
     * The specific snippet of code:
     *   		die "No supported Python implementation in PYTHON_SINGLE_TARGET/PYTHON_TARGETS."
     * 
     * If you need support, post the output of `emerge --info '=games-emulation/retroarch-9999::abendbrot'`,
     * the complete build log and the output of `emerge -pqv '=games-emulation/retroarch-9999::abendbrot'`.
     * The complete build log is located at '/var/tmp/portage/games-emulation/retroarch-9999/temp/build.log.gz'.
     * The ebuild environment file is located at '/var/tmp/portage/games-emulation/retroarch-9999/temp/die.env'.
     * Working directory: '/usr/lib64/python3.3/site-packages'
     * S: '/var/tmp/portage/games-emulation/retroarch-9999/work/retroarch-9999'
    
    >>> Failed to emerge games-emulation/retroarch-9999, Log file:
    
    >>>  '/var/tmp/portage/games-emulation/retroarch-9999/temp/build.log.gz'

Contrary to the error message, the `PYTHON_SINGLE_TARGET` variable should *never* be explicitly set – either in `make.conf` *or* `package.use`. Rather, the ebuild itself should be patched to enable either the `python_single_target_python3_3` *or* `python_single_target_python3_4` USE flag (but not both) by default.

Happily, I've fixed this locally and will be submitting a pull request shortly.

**Comment by stefan-gr** [comment]
Thank you for the patch, will merge your pull request soon.
