### ISSUE TITLE
games-emulation/retroarch: Installation Fundamentally Broken

### ISSUE THREAD

**Issue by leycec** [stefan-gr/abendbrot#27]
The `src_install` phase of `retroarch` appears to be fundamentally broken:

    >>> Install retroarch-9999 into /var/tmp/portage/games-emulation/retroarch-9999/image/ category games-emulation
    make -j3 -l1.95 DESTDIR=/var/tmp/portage/games-emulation/retroarch-9999/image/ install 
    CC git_version.c
    LD retroarch
    rm -f obj-unix/git_version.o
    mkdir -p /var/tmp/portage/games-emulation/retroarch-9999/image//usr/games/bin 2>/dev/null || /bin/true
    mkdir -p /var/tmp/portage/games-emulation/retroarch-9999/image//etc 2>/dev/null || /bin/true
    mkdir -p /var/tmp/portage/games-emulation/retroarch-9999/image//usr/share/man/man1 2>/dev/null || /bin/true
    mkdir -p /var/tmp/portage/games-emulation/retroarch-9999/image//usr/share/pixmaps 2>/dev/null || /bin/true
    install -m755 retroarch /var/tmp/portage/games-emulation/retroarch-9999/image//usr/games/bin 
    install -m755 tools/cg2glsl.py /var/tmp/portage/games-emulation/retroarch-9999/image//usr/games/bin/retroarch-cg2glsl
    install -m755 tools/retroarch-joyconfig  /var/tmp/portage/games-emulation/retroarch-9999/image//usr/games/bin
    install -m644 retroarch.cfg /var/tmp/portage/games-emulation/retroarch-9999/image//etc/retroarch.cfg
    install -m644 docs/retroarch.1 /var/tmp/portage/games-emulation/retroarch-9999/image//usr/share/man/man1
    install -m644 docs/retroarch-cg2glsl.1 /var/tmp/portage/games-emulation/retroarch-9999/image//usr/share/man/man1
    install -m644 docs/retroarch-joyconfig.1 /var/tmp/portage/games-emulation/retroarch-9999/image//usr/share/man/man1
    install -m644 media/retroarch.png /var/tmp/portage/games-emulation/retroarch-9999/image//usr/share/pixmaps
    install -m644 media/retroarch.svg /var/tmp/portage/games-emulation/retroarch-9999/image//usr/share/pixmaps
    >>> Completed installing retroarch-9999 into /var/tmp/portage/games-emulation/retroarch-9999/image/

    Files matching a file type that is not allowed:
       usr/lib/retroarch/filters/video/2xsai.so
       usr/lib/retroarch/filters/video/2xbr.so
       usr/lib/retroarch/filters/video/scale2x.so
       usr/lib/retroarch/filters/video/super2xsai.so
       usr/lib/retroarch/filters/video/epx.so
       usr/lib/retroarch/filters/video/darken.so
       usr/lib/retroarch/filters/video/lq2x.so
       usr/lib/retroarch/filters/video/blargg_ntsc_snes.so
       usr/lib/retroarch/filters/video/phosphor2x.so
       usr/lib/retroarch/filters/video/supereagle.so
       usr/lib/retroarch/filters/audio/echo.so
       usr/lib/retroarch/filters/audio/wahwah.so
       usr/lib/retroarch/filters/audio/reverb.so
       usr/lib/retroarch/filters/audio/phaser.so
       usr/lib/retroarch/filters/audio/iir.so
       usr/lib/retroarch/filters/audio/chorus.so
       usr/lib/retroarch/filters/audio/panning.so
       usr/lib/retroarch/filters/audio/eq.so
     * ERROR: games-emulation/retroarch-9999::abendbrot failed:
     *   multilib-strict check failed!
     * 
     * Call stack:
     *   misc-functions.sh, line 558:  Called install_qa_check
     *   misc-functions.sh, line 181:  Called source 'install_symlink_html_docs'
     *   80multilib-strict, line  47:  Called multilib_strict_check
     *   80multilib-strict, line  43:  Called die
     * The specific snippet of code:
     *   		[[ ${abort} == yes ]] && die "multilib-strict check failed!"
     * 
     * If you need support, post the output of `emerge --info '=games-emulation/retroarch-9999::abendbrot'`,
     * the complete build log and the output of `emerge -pqv '=games-emulation/retroarch-9999::abendbrot'`.
     * The complete build log is located at '/var/tmp/portage/games-emulation/retroarch-9999/temp/build.log.gz'.
     * The ebuild environment file is located at '/var/tmp/portage/games-emulation/retroarch-9999/temp/environment'.
     * Working directory: '/var/tmp/portage/games-emulation/retroarch-9999/image'
     * S: '/var/tmp/portage/games-emulation/retroarch-9999/work/retroarch-9999'
    !!! post install failed; exiting.
    
    >>> Failed to emerge games-emulation/retroarch-9999, Log file:
    
    >>>  '/var/tmp/portage/games-emulation/retroarch-9999/temp/build.log.gz'

The solution *should* be fairly simple. The ebuild needs to be made `multilib`-compliant, such that shared libraries are installed to `/usr/lib64/retroarch` under 64-bit machines and `/usr/lib32/retroarch` under 32-bit machines.

After fixing this locally, I'll submit a pull request correcting both this and issue #26.

**Comment by stefan-gr** [comment]
Thank you for introducing me to the multilib-strict feature, that should take care of my sloppy use of get_libdir. I will get to merge your pull request in short order.
