### ISSUE TITLE
games-emulation/retroarch: x11-drivers/xf86-input-evdev is only required iff "X" and "udev" USE flags are both enabled

### ISSUE THREAD

**Issue by joao-o** [stefan-gr/abendbrot#35]
As said in the title x11-drivers/xf86-input-evdev is only required if both "X" and "udev" are enabled.
Having X without udev can happen if you use mdev or smdev as the device manager. 
This dependency prevents building retroarch with X support if you do not have udev
installed.

**Comment by stefan-gr** [comment]
Thanks for the heads up, I can't test it properly at the moment but this should do it.
Please reopen if the need arises.

Have a nice day.
