### ISSUE TITLE
bsnes-libretro-9999-r1 fails portage sanity checks

### ISSUE THREAD

**Issue by yoshi314** [stefan-gr/abendbrot#36]
`Calculating dependencies \ * ERROR: games-emulation/bsnes-libretro-9999-r1::abendbrot failed (depend phase):
 *   use() calls are not allowed in global scope
 * 
 * Call stack:
 *                       ebuild.sh, line 606:  Called source '/mnt/storage/overlays/abendbrot/games-emulation/bsnes-libretro/bsnes-libretro-9999-r1.ebuild'
 *   bsnes-libretro-9999-r1.ebuild, line  28:  Called use 'profile_accuracy'
 *                       ebuild.sh, line  78:  Called die
 * The specific snippet of code:
 *   		eval "${x}() { die \"\${FUNCNAME}() calls are not allowed in global scope\"; }"
 * 
 * If you need support, post the output of `emerge --info '=games-emulation/bsnes-libretro-9999-r1::abendbrot'`,
 * the complete build log and the output of `emerge -pqv '=games-emulation/bsnes-libretro-9999-r1::abendbrot'`.
 * Working directory: '/usr/lib64/python3.4/site-packages'
 * S: '/mnt/storage/tmp/portage/games-emulation/bsnes-libretro-9999-r1/work/bsnes-libretro-9999'`

**Comment by stefan-gr** [comment]
Thanks for the heads up,
it should be fixed now.
