### ISSUE TITLE
retroarch fail to build with vulkan

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#39]
vulkan don't need the "media-libs/mesa:0=[vulkan?]" dependency, especially if you are using closed source ati/nvidia drivers, but it needs "vulkan-base" ( you can find an ebuild there : https://574886.bugs.gentoo.org/attachment.cgi?id=437546 )

**Comment by barbudreadmon** [comment]
also, you would need a separate ebuild which is a duplicate of mupen64 with a few changes ("HAVE_VULKAN=1" always included, gles2 useless since gles2 doesn't support vulkan, perhaps replace it with a gles3 use flag ?) for "parallel-libretro" the n64 libretro core with vulkan support

**Comment by stefan-gr** [comment]
Thanks, I can't test vulkan since my hardware is too old. But the changes I made build for me, could you see if that works as intended? Also, do we need the slang-shaders for vulkan?

**Comment by barbudreadmon** [comment]
Yes, parallel-libretro won't accept common-shaders, but you still need both (slang-shaders for vulkan-enabled libretro cores, common-shaders for the others). I didn't try your new ebuilds yet, i'll let you know when i try them.

**Comment by barbudreadmon** [comment]
Ok, everything seems to work fine, i encountered 2 issue but they are from upstream : 
- retroarch 1.3.6 does not allow to select vulkan as video driver in retroarch menu, you have to edit retroarch config file manually.
- i can't load zip files (except with mame/fba cores, probably because this is built-in in those cores) with retroarch-9999.

Also, i noticed every core except those specifically written for opengl (i only found mupen64-libretro to be such a core, but i didn't test all of them) will work with vulkan video driver, which makes me wonder if common-shaders is really usefull when you build retroarch with vulkan support.

**Comment by stefan-gr** [comment]
That's interesting, I can select vulkan as video driver per gui. But it segfaults for me since I don't have a vulkan gpu. Did you update the retroarch ebuild before testing? I made some changes to use git since the submodules are not included in the released tarballs from github.

It probably makes sense to only depend on common-shaders when vulkan is not set and vice versa. I will make retroarch.cfg changes depending on that to have a working first install with vulkan flag.

**Comment by barbudreadmon** [comment]
I confirm vulkan is available from menu now in retroarch-1.3.6.
Also, retroarch-9999 will load zip files now.
