### ISSUE TITLE
Filter out -Ox cflag from fbalpha-libretro

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#42]
fbalpha2012 is probably affected too.
Some games won't work with -O3 in cflags, i'm not sure debug work properly if you don't filter -Ox cflags either since it needs -O0, and anyway this cflag is appended through makefile.libretro depending if you build for debug or not, so we should probably just filter them all out.

Yeah i know, i have been asking a lot of things lately :)

**Comment by stefan-gr** [comment]
Yes something has to be done about this. I have noticed that almost all cores apply the same/similar flags with DEBUG=0/1. We would probably need to disable system -O*  for every ebuild or modify the makefiles directly to make them obey system optimization, apart from DEBUG=1 of course.

As a gentoo user I want ebuilds to obey make.conf and only disallow -O* when it is know to cause breakage. Either way, I have to do something about the multiple flags when debug is set.

Have your proposed changes in the meantime. I will look into the debug thing tomorrow.

**Comment by stefan-gr** [comment]
Alright, I will not modify the makefiles. It's really too bothersome to maintain 55 patches.
I modified all ebuilds that have custom -O* in their makefiles to filter out all -O*, as you suggested.
Now all the -O* spam from gcc should end.
> Yeah i know, i have been asking a lot of things lately :)

Don't worry about that. It helps to prevent me from becoming lazy. ;^)

**Comment by sjnewbury** [comment]
You know, it's funny, but I have patched your ebuild to automatically patch each upstream source to respect the portage CFLAGS and fbalpha-libretro works fine for me. (I use really extreme flags including unconditionally linking pretty much everything with jemalloc!)  I've been meaning to create a pull request, although it's a bit on the hacky side.

**Comment by barbudreadmon** [comment]
Some games won't work with something above -O2, try hbarrel and you'll see.

**Comment by stefan-gr** [comment]
My end goal was to provide a `USE="custom-cflags" `like in firefox for all cores that specify their own. That would make sure that bugs in the cores can be easier up streamed since I don't think we would get much support for custom builds for some cores.

Please push what you have and we can hack together on that if you want, though the default should be to obey upstream. Perhaps there can be some sort of automatic patching in the eclass if `USE="custom-cflags" ` is enabled

**Comment by sjnewbury** [comment]
On Wed, 2016-12-21 at 07:09 -0800, stefan-gr wrote:
> My end goal was to provide a USE="custom-cflags"like in firefox for
> all cores that specify their own. That would make sure that bugs in
> the cores can be easier up streamed since I don't think we would get
> much support for custom builds for some cores.
> Please push what you have and we can hack together on that if you
> want, though the default should be to obey upstream. Perhaps there
> can be some sort of automatic patching in the eclass if USE="custom-
> cflags" is enabled
Protecting it with custom-cflags is a good idea.  I'll do that, then
send you a pull request.
