### ISSUE TITLE
need miniupnpc use flag

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#49]
We need a use flag for miniupnpc support, currently the configure script will enable it if it is present on your system, but the build will fail with the following message : 
`libretro-common/net/net_natt.c:55:14: error: too few arguments to function ‘upnpDiscover’
    devlist = upnpDiscover(2000, NULL, NULL, 0, 0, &upnperror);
`

**Comment by barbudreadmon** [comment]
Seems like miniupnpc < 1.9 is needed to build successfully.

**Comment by stefan-gr** [comment]
What a short life this flag had, looks like we need to wait for miniupnpc 2.0 according to your bug report libretro/RetroArch/issues/4156.

**Comment by barbudreadmon** [comment]
Hmm there are a few third-party repo providing miniupnpc-2.0 (http://gpo.zugaina.org/net-libs/miniupnpc), perhaps it could be a good idea to keep the use flag and copy one of their ebuild into your repo ?

**Comment by stefan-gr** [comment]
I put it there for you but I needed to change some APIVERSION modifications of the original ebuild since retroarch looks for > 16. It has no keywords so you need to add it to packages.keywords.

If you get blocks just `emerge -1 miniupnpc retroarch`
