### ISSUE TITLE
beetle-psx-libretro doesn't enable hardware support

### ISSUE THREAD

**Issue by chewi** [stefan-gr/abendbrot#51]
This doesn't appear to be documented anywhere but Beetle PSX doesn't enable hardware support by default. You can pass `HAVE_HW=1` to `emake` but this enables both OpenGL and Vulkan. You may want to add `opengl` and `vulkan` USE flags to pass `HAVE_OPENGL=1` and `HAVE_VULKAN=1` instead but you will also need to `append-cppflags -DHAVE_HW`. The good news is it does appear to respect `CPPFLAGS`. The resulting library filename changes when you do this so you could `mv ${S}"/mednafen_psx*_libretro.so` in `src_install`.

**Comment by stefan-gr** [comment]
Thanks, this should work as of e13bde5.
