### ISSUE TITLE
games-emulation/mame-libretro-1.0_pre20161121 needs GCC 5

### ISSUE THREAD

**Issue by Jannis234** [stefan-gr/abendbrot#56]
The latest version of mame-libretro refuses to build when using GCC 4.X (it prints "GCC version 5.0 or later needed" and aborts). It might be a good idea to add >=sys-devel/gcc-5.0 to DEPEND.

**Comment by stefan-gr** [comment]
Thanks for the report,
I will look into updating the ebuild.
