### ISSUE TITLE
retroarch-9999-r3 fail to build

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#58]
> rm darken.o 2xsai.o blargg_ntsc_snes.o super2xsai.o lq2x.o 2xbr.o scale2x.o epx.o phosphor2x.o supereagle.o
make: Leaving directory '/var/tmp/portage/games-emulation/retroarch-9999-r3/work/retroarch-9999/gfx/video_filters'
make -j5 build=release -C audio/audio_filters/
make: *** audio/audio_filters/: No such file or directory.  Stop.

it seems audio/audio_filters/ was moved to audio/dsp_filters/

**Comment by jason-oliveira** [comment]
It seems there is no audio/dsp_filters/ nor audio/audio_filters in current git. line needs to be commented-out

**Comment by stefan-gr** [comment]
Thanks for the report. It should be solved with b33e51bcf9aa118ba2a84158ae6e463a83c3abc9.
