### ISSUE TITLE
parallel now using its own repository + feature request

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#60]
I noticed parallel-n64 got splitted from mupen64, here is its repository : https://github.com/libretro/parallel-n64

Also, i think it would be a great idea to add an ebuild for beetle-saturn, perhaps going as far as using it as the default saturn emulator in use flags. The mrboom (a bomberman 8 players clone) and mame2003 (for low performance hardware, mame2000 is getting kinda old, people now prefer using fbalpha + mame2003) cores would be some nice additions too.

**Comment by stefan-gr** [comment]
Whew, this repo renaming/moving around upstream was kinda confusing at first. I hope everything is alright now.
Thanks for the report.
