### ISSUE TITLE
[request] melonDS and sameboy libretro cores

### ISSUE THREAD

**Issue by kabili207** [stefan-gr/abendbrot#69]
Libretro [has announced](https://www.libretro.com/index.php/more-new-cores-melonds-sameboy/) two new cores, [melonDS](https://github.com/libretro/melonDS) and [SameBoy](https://github.com/libretro/SameBoy). Can you create ebuilds for these cores?

**Comment by stefan-gr** [comment]
Thanks for the heads up.
