### ISSUE TITLE
retroarch-assets fetch failure

### ISSUE THREAD

**Issue by lucasmr** [stefan-gr/abendbrot#81]
Tested on two machines.

> >>> Emerging (2 of 50) games-emulation/retroarch-assets-1.0_pre20170727::abendbrot
>  * Fetching files in the background.
>  * To view fetch progress, run in another terminal:
>  * tail -f /var/log/emerge-fetch.log
> >>> Downloading 'https://github.com/libretro/retroarch-assets/archive/8fd7361b09edfe317
> b8208c1c3051bc2aafa99f9.tar.gz'
> --2017-09-27 16:38:59--  https://github.com/libretro/retroarch-assets/archive/8fd7361b0
> 9edfe317b8208c1c3051bc2aafa99f9.tar.gz
> Resolving github.com... 192.30.253.112, 192.30.253.113
> Connecting to github.com|192.30.253.112|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://codeload.github.com/libretro/retroarch-assets/tar.gz/8fd7361b09edfe31
> 7b8208c1c3051bc2aafa99f9 [following]
> --2017-09-27 16:38:59--  https://codeload.github.com/libretro/retroarch-assets/tar.gz/8fd7361b09edfe317b8208c1c3051bc2aafa99f9
> Resolving codeload.github.com... 192.30.253.120, 192.30.253.121
> Connecting to codeload.github.com|192.30.253.120|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [application/x-gzip]
> Saving to: '/usr/portage/distfiles/retroarch-assets-1.0_pre20170727.tar.gz'
> /usr/portage/distfi     [        <=>         ]  73.17M  5.99MB/s    in 26s
> 
> 2017-09-27 16:39:26 (2.79 MB/s) - '/usr/portage/distfiles/retroarch-assets-1.0_pre20170
> 727.tar.gz' saved [76728046]
> 
> !!! Fetched file: retroarch-assets-1.0_pre20170727.tar.gz VERIFY FAILED!
> !!! Reason: Filesize does not match recorded size
> !!! Got:      76728046
> !!! Expected: 76728052
> Refetching... File renamed to '/usr/portage/distfiles/retroarch-assets-1.0_pre20170727.
> tar.gz._checksum_failure_.eecy8ex1'

**Comment by stefan-gr** [comment]
Thanks for the heads up.
