### ISSUE TITLE
Build issue with USE="mupen64plus"

### ISSUE THREAD

**Issue by lucasmr** [stefan-gr/abendbrot#82]
```
In file included from GLideN64/src/GLideNHQ/TxHiResCache.h:35:0,                    +       }
                 from GLideN64/src/GLideNHQ/TxFilter.h:29,                          +
                 from GLideN64/src/GLideNHQ/TxFilter.cpp:33:                        +       return LATENCY_MULTIPLIER;
GLideN64/src/GLideNHQ/TxImage.h:28:17: fatal error: png.h: No such file or director +}
y                                                                                   +EXPORT_SYMBOL_GPL(cpufreq_policy_transition_delay_us);
compilation terminated.
make: *** [Makefile:317: GLideN64/src/GLideNHQ/TxFilter.o] Error 1                   /*********************************************************************
 * ERROR: games-emulation/mupen64plus-libretro-1.0_pre20170522::abendbrot failed (c   *                          SYSFS INTERFACE                          *
ompile phas
```

I find it odd that the mupen64plus USE flag is building mupen64plus-libretro, because this version doesn't pull the GlideN64 plugin according to the mupen64plus-libretro repository: "Mupen64Plus uses GLideN64 (a graphics plugin that is not available in mupen64plus-libretro). "

Maybe a new USE flag called mupen64plus-libretro would be more appropriate.

**Comment by stefan-gr** [comment]
Thanks for the report.
I added libpng as dependency, that should fix it.
If you want to have hardware accelerated mupen64plus then you should USE="parallel", that's the one with vulkan/opengl/gles support, the default flags for it should provide you with plenty of plugins.

The USE flags for libretro-meta use the repository/core names to make managing them easier, especially since they are called like this inside retroarch.

**Comment by lucasmr** [comment]
```
nasm -f elf -d ELF_TYPE mupen64plus-core/src/r4300/new_dynarec/x86/linkage_x86.asm -o mupen64plus-core/src/r4300/new_dynarec/x86/linkage_x86.o
make: nasm: Command not found
make: *** [Makefile:308: mupen64plus-core/src/r4300/new_dynarec/x86/linkage_x86.o] Error 127

```

Adding dev-lang/nasm would fix this as well.

Thanks!
