### ISSUE TITLE
retroarch-1.6.9 - tad more than a version bump.

### ISSUE THREAD

**Issue by jason-oliveira** [stefan-gr/abendbrot#85]
retroarch-1.6.9-build.patch is broken, as orbea rewrote to explicitly die in commit https://github.com/libretro/RetroArch/commit/bf8863d36055a12b8f2cd1fbd5be7f84d17b0dca#diff-546edcf091f4cb2bca9608b42cdc1534

from #retroarch on freenode:
‎[16:35] ‎<‎orbea‎>‎ anyways if you want to repatch it, just it from die 1 to die :
‎[16:35] ‎<‎orbea‎>‎ wont exit

seems my patch-fu is weak, otherwise I'd just fix it myself and submit a pull request.
if it helps, the commit hash you'll want to use for 1.6.9 is 6f5cad5f5993e27fc1daa5e5e04f1749164f9a1c

**Comment by jason-oliveira** [comment]
https://github.com/libretro/RetroArch/pull/5750/commits/8ab308d9ddc34361ebf078d3d954875387445498

issue was resolved, patch will likely not be needed in next version of retroarch.

**Comment by stefan-gr** [comment]
Thanks for the report.
It's on gentoo to patch upstream to make it not die on unknown build options. econf drops often used build options on the build system in hopes that something sticks and obeys local customs like EROOT and things. It's pretty useful, if the build system can handle it, but we can't expect upstream to no-op every single unknown option from gentoo.
