### ISSUE TITLE
retroarch ebuild specifies wrong default PYTHON_SINGLE_TARGET, causes portage block by default

### ISSUE THREAD

**Issue by lucianposton** [stefan-gr/abendbrot#86]
Since the ebuild specifies IUSE=+python_single_target_python3_4 , if the profile changes the default PYTHON_SINGLE_TARGET, which it did recently, portage fails to resolve the ebuild's dependencies without the use manually adjusting USE flags.

Instead of specifying a default, just remove PYTHON_SINGLE_TARGET from IUSE, deferring to the values set by python-single-r1.eclass, which you already use.

https://github.com/stefan-gr/abendbrot/blob/70913af16937dc2e04c687ec03edace97f2236c1/games-emulation/retroarch/retroarch-1.6.7.ebuild#L26-L29

**Comment by stefan-gr** [comment]
Thanks for this,
I never expected to get out of this mess.
