### ISSUE TITLE
retroarch-1.6.7 ebuild broken

### ISSUE THREAD

**Issue by lucianposton** [stefan-gr/abendbrot#87]
The change below broke retroarch-1.6.7 (the highest unmasked version, currently) and lower versions since the ebuilds don't set SRC_URI and SRC_URI isn't set in the eclass due to the conditional change.

https://github.com/stefan-gr/abendbrot/commit/3b542fdbe8aa1cc51a0f38ad2d8ea15613feac8a#diff-74086e8fc7ebfdb25a58713e51210fbdR51

**Comment by stefan-gr** [comment]
Thanks for the report,
I knew I forgot something, sorry about that.
