### ISSUE TITLE
retroarch-1.7.0 version bump

### ISSUE THREAD

**Issue by jason-oliveira** [stefan-gr/abendbrot#91]
making a new symlink to the new version works fine. However, the build patch is no longer needed, due to upstream changes from https://github.com/stefan-gr/abendbrot/issues/85

**Comment by samcv** [comment]
@stefan-gr bumping in case you have not seen this yet. Thank you for maintaining these ebuilds!

**Comment by crocket** [comment]
The latest stable version of retroarch is 1.7.1

**Comment by stefan-gr** [comment]
I did a crude bump with no KEYWORD. I don't have gentoo at the moment so I couldn't test this. Please see if this works out.

**Comment by crocket** [comment]
1.7.1 builds and runs well. I just ran a dreamcast game on 1.7.1

**Comment by stefan-gr** [comment]
Thanks for trying it out @crocket .
Also, @jason-oliveira  the last time I tried to drop the build patch broke the configure phase because there are too many unknown options from econf. BUILD doesn't seem enough to make the build script happy. Did you have different results?
