### ISSUE TITLE
games-emulation/desmume-libretro is broken.

### ISSUE THREAD

**Issue by crocket** [stefan-gr/abendbrot#94]
desmume-libretro-1.0_pre20170907.ebuild and
desmume-libretro-1.0_pre20171024.ebuild point to git commits that are not existent in actual repository.

desmume-libretro-9999-r2 doesn't compile.

When I try to compile -9999-r2, I see the following error message.

```
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by stefan-gr** [comment]
Thanks for the report,
desmume got rebased and split into different repos. I hope I got the checksums right.

**Comment by lucianposton** [comment]
@stefan-gr  There are still some ebuilds in the repo that depend on the desmume-libretro atom e.g. libretro-meta

**Comment by stefan-gr** [comment]
Thanks for the heads up.

**Comment by crocket** [comment]
The build fails

```
 * ERROR: games-emulation/desmume2015-libretro-1.0_pre20170907::abendbrot failed (install phase):
 *   Libretro core shared library "/var/tmp/portage/games-emulation/desmume2015-libretro-1.0_pre20170907/image//usr/lib64/libretro/desmume2015_libretro.so" not installed.
 *
 * Call stack:
 *     ebuild.sh, line  124:  Called src_install
 *   environment, line 2276:  Called libretro-core_src_install
 *   environment, line 1484:  Called die
 * The specific snippet of code:
 *               [[ -f "${lib_file_target}" ]] || die "Libretro core shared library \"${lib_file_target}\" not installed.";
```

```
 * ERROR: games-emulation/desmume2015-libretro-1.0_pre20171024::abendbrot failed (install phase):
 *   Libretro core shared library "/var/tmp/portage/games-emulation/desmume2015-libretro-1.0_pre20171024/image//usr/lib64/libretro/desmume2015_libretro.so" not installed.
 *
 * Call stack:
 *     ebuild.sh, line  124:  Called src_install
 *   environment, line 2276:  Called libretro-core_src_install
 *   environment, line 1484:  Called die
 * The specific snippet of code:
 *               [[ -f "${lib_file_target}" ]] || die "Libretro core shared library \"${lib_file_target}\" not installed.";
```

**Comment by crocket** [comment]
It seems both versions produce desmume-libretro.so instead of desmume2015-libretro.so

**Comment by stefan-gr** [comment]
Everything is untested but I thing this should work now.

**Comment by crocket** [comment]
What are the differences between https://github.com/libretro/desmume and https://github.com/libretro/desmume2015? In my naive perspective, desmume should be more recent than desmume2015. It's 2018. I want the cores from latest stable releases.

**Comment by crocket** [comment]
I can build `games-emulation/desmume-libretro-1.0_pre20180311`, but I haven't tested games on desmume core, yet.

**Comment by crocket** [comment]
`games-emulation/desmume-libretro-9999-r2` can also be built on my machine.

**Comment by stefan-gr** [comment]
Nice, I hope it also produces a usable core.

**Comment by crocket** [comment]
I just played a GameCube game with `games-emulation/desmume-libretro-1.0_pre20180311` for a few minutes. It worked.

**Comment by stefan-gr** [comment]
It can play gamecube games? Wow, I didn't know that.

**Comment by stefan-gr** [comment]
Woops, forgot to close this. Thanks for reporting this.
