### ISSUE TITLE
games-emulation/mednafen-saturn-libretro with opengl USE flag produces mednafen_saturn_hw_libretro.so which isn't in core info database

### ISSUE THREAD

**Issue by crocket** [stefan-gr/abendbrot#98]
But, mednafen_saturn_libretro.so is in core info database.

https://github.com/libretro/libretro-core-info/issues/8 tracks this issue.

**Comment by stefan-gr** [comment]
I see, it wasn't a supported configuration.
I just renamed the TARGET to the default one for the time being.

**Comment by crocket** [comment]
It seems mednafen-saturn-libretro's Makefile is a generic makefile that has `HAVE_OPENGL` option in every libretro core. mednafen-saturn-libretro doesn't have OpenGL support, yet. I think it makes sense to remove `opengl` USE flag from the package.

**Comment by stefan-gr** [comment]
Done, thanks for reporting this.
